version: '3'
services:
    app:
        image: jamesdbloom/mockserver
        ports:
            # avoid clash with mailcatcher
            - 2080:1080
        restart: always
    configure:
        image: appropriate/curl
        entrypoint: /bin/sh -c "
            while ! nc -z app 1080; do sleep 1; done;
            find /expectations -name '*.sh' -exec sh {} \; ;
            exec sleep 365d"
        volumes:
            - ./expectations/:/expectations
        restart: always
        depends_on:
            - app
