version: '3'
services:
    {{ name|replace("-", "_") }}:
        container_name: {{ name|replace("-", "_") }}
        image: {{ image }}:${IMAGE_TAG}
        {% if command %}
        command: {{ command }}
        {% endif %}
        networks:
            - sidecars
        {%- if port %}
        ports:
            - {{ port }}:8080
        {%- elif ports %}
        ports:
            {%- for p in ports %}
            - {{ p|yaml }}
            {%- endfor %}
        {%- endif %}
        {%- if volumes %}
        volumes:
            {%- for v in volumes %}
            - {{ v|yaml }}
            {%- endfor %}
        {%- endif %}
        restart: always

networks:
    sidecars:
        external: true
