#!/bin/bash
set -e # everything must pass
set -u # no unbound variables

current_date=$(date -I)
created_file="/root/highstate-${current_date}"

if [ -e "${created_file}" ]; then
    echo "Already run: ${created_file}"
    exit 0
fi

log_file=/var/log/daily-system-update.log
set -o pipefail
sudo timeout 60m salt-call --force-color state.highstate -l info --retcode-passthrough | tee $log_file || {
    status=$?
    echo "Error in daily-system-update, state.highstate returned: ${status}"
    logger "Salt highstate failure: $log_file on $(hostname)"
    exit $status
}
touch "${created_file}"

