#!/bin/bash
set -e

docker container prune --force
docker network prune --force
docker volume prune --force

echo "Clean up all images not used in the last 14 days"
docker image prune -a --filter "until=336h" --force
