#!/bin/bash
set -e

docker container prune -f
docker network prune -f
docker volume prune -f

echo "Clean up all images not used in the last 14 days"
docker image prune -a --filter "until=336h" -f

# https://github.com/moby/moby/issues/9054#issuecomment-227920187
#images="/tmp/$(date +%Y-%m-%dT%H:%M:%S).txt"
#docker images | grep -v REPOSITORY | awk '{print $3}' | xargs -n 1 docker history | grep -v missing | grep -v "^IMAGE" | egrep -v "day|hour|minute|second" | awk '{print $1}' | sort | uniq > "$images"
#cat "$images" | xargs -n 1 docker inspect | jq -r .[0].RepoTags[] | xargs docker rmi
