#!/bin/bash
set -e

# default: 14 days
hours_limit="${1:-336}"

docker container prune --filter "until=${hours_limit}h" --force
docker network prune --filter "until=${hours_limit}h" --force
# doesn't support --filter "until=..."
docker volume prune --force

echo "Clean up all images not used in the last $hours_limit hours"
docker image prune --all --filter "until=${hours_limit}h" --force
